CREATE TABLE [sec].[Role]
(
	[Id] INT IDENTITY(1,1) NOT NULL PRIMARY KEY,
	[Name] NVARCHAR(256) NOT NULL,
	[Description] NVARCHAR(512) NULL,
	[IsActive] BIT NOT NULL DEFAULT(1),
	[CreatedAt] DATETIME2 NOT NULL DEFAULT(GETUTCDATE()),
	[CreatedBy] NVARCHAR(256) NOT NULL,
	[UpdatedAt] DATETIME2 NULL,
	[UpdatedBy] NVARCHAR(256) NULL,
	[DeletedAt] DATETIME2 NULL,
	[DeletedBy] NVARCHAR(256) NULL
)
