CREATE TABLE [sec].[User]
(
	[Id] INT IDENTITY(1,1) NOT NULL PRIMARY KEY,
	[Username] NVARCHAR(256) NOT NULL,
	[FirstName] NVARCHAR(128) NOT NULL,
	[LastName] NVARCHAR(128) NOT NULL,
	[PhoneNumber] NVARCHAR(128) NULL,
	[Email] NVARCHAR(256) NULL,
	[Salt] NVARCHAR(256) NOT NULL,
	[PasswordHash] NVARCHAR(512) NOT NULL,
	[LastLogin] DATETIME2 NULL,
	[IsActive] BIT NOT NULL DEFAULT(1),
	[CreatedAt] DATETIME2 NOT NULL DEFAULT(GETUTCDATE()),
	[CreatedBy] NVARCHAR(256) NOT NULL,
	[UpdatedAt] DATETIME2 NULL,
	[UpdatedBy] NVARCHAR(256) NULL,
	[DeletedAt] DATETIME2 NULL,
	[DeletedBy] NVARCHAR(256) NULL
);
