name: Build Check

on:
  push:
    branches: [development]
  pull_request:
    branches: [development]

jobs:
  build:
    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v4

    - name: Setup MSBuild
      uses: microsoft/setup-msbuild@v2

    - name: Build DACPAC
      run: msbuild powdernaut.database/powdernaut.database.sqlproj /p:Configuration=Release
